# GLOBAL SITE SETTINGS

cname: erbas.yourwebvisual.com

# META
title: Erbas
title_homepage: Erbas - Engineers for Building Services
company: Erbas
description: Engineers for Building Services

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/erba-0417
github_repo_name: erba-0417
jekyll_version: 3.0.3

# OFFICES
offices:
  - title: Sydney
    address: Level 1,<br>15 Atchison Street,<br>St Leonards, NSW 2065
    phone: +61 2 9437 1022
    email: general@erbas.com.au

  - title: Melbourne
    address: Level 13,<br>200 Queen Street,<br>Melbourne, VIC 3000
    phone: +61 3 8648 6538
    email: general@erbas.com.au

  - title: Manilla
    address: Suite 2403, Union Bank Plaza,<br>Meralco Ave, Ortigas,<br>Pasig City, Philippines
    phone: +63 2483 0770
    email: general@erbas.com.au

# SOCIAL MEDIA
facebook:
linked_in:
google_plus:
instagram:

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://muchmedia.com.au
  logo: /assets/img/ui/much-media-logo.svg
  description: Website by Much Media